CREATE TABLE DEPT_tmp AS SELECT * FROM dept; 
SELECT * FROM DEPT_tmp;

-- UPDATE ~ SET
UPDATE DEPT_tmp SET LOC = 'SEOUL';		-- 해당 열 전체 수정
UPDATE DEPT_tmp SET DNAME = 'DATABASE', LOC = 'PUSAN' WHERE DEPTNO = 40;		-- 일부 열 수정
-- 서브쿼리를 사용한 데이터 수정
UPDATE DEPT_tmp SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT_tmp WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

-- DELETE 
CREATE TABLE EMP_TMP AS SELECT * FROM EMP;
SELECT * FROM EMP_TMP;
DELETE FROM EMP_TMP WHERE JOB = 'SALESMAN';

-- 서브 쿼리 삭제
DELETE FROM EMP_TMP;
SELECT * FROM EMP_TMP;
DROP TABLE EMP_TMP; 

-- 트랜잭션
CREATE TABLE DEPT_TMP;
SELECT * FROM TAB;
SELECT * FROM DEPT_TMP;

CREATE TABLE DEPT_TCL 
AS SELECT * FROM DEPT D;
SELECT * FROM DEPT_TCL;

INSERT INTO DEPT_TCL VALUES(50, 'DATABASE','BUSAN');
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;
DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

-- 트랜잭션이 실행중일 때는 LOCK이 걸린다.
ROLLBACK;			-- 트랜잭션 취소
COMMIT; 			-- 트랜잭션 반영
DROP TABLE DEPT_TCL;

-- VIEW
CREATE VIEW VM_EMP AS (SELECT EMPNO, ENAME, JOB, DEPTNO FROM EMP e WHERE DEPTNO = 20);
SELECT * FROM VM_EMP;
SELECT * FROM USER_VIEWS;
DROP VIEW VM_EMP;


-- 테이블, 데이터사전, 인덱스, 뷰, 시퀀스 동의어
SELECT * FROM DICT;				-- 사용가능한 데이터 사전
SELECT TABLE_NAME FROM USER_TABLES;
SELECT OWNER, TABLE_NAME FROM ALL_TABLES;
SELECT * FROM DBA_TABLES;

-- 시퀀스





