CREATE TABLE DEPT_tmp AS SELECT * FROM dept; 
SELECT * FROM DEPT_tmp;

-- UPDATE ~ SET
UPDATE DEPT_tmp SET LOC = 'SEOUL';		-- 해당 열 전체 수정
UPDATE DEPT_tmp SET DNAME = 'DATABASE', LOC = 'PUSAN' WHERE DEPTNO = 40;		-- 일부 열 수정
-- 서브쿼리를 사용한 데이터 수정
UPDATE DEPT_tmp SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT_tmp WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

-- DELETE 
CREATE TABLE EMP_TMP AS SELECT * FROM EMP;
SELECT * FROM EMP_TMP;
DELETE FROM EMP_TMP WHERE JOB = 'SALESMAN';

-- 서브 쿼리 삭제
DELETE FROM EMP_TMP;
SELECT * FROM EMP_TMP;
DROP TABLE EMP_TMP; 

-- 트랜잭션
CREATE TABLE DEPT_TMP;
SELECT * FROM TAB;
SELECT * FROM DEPT_TMP;

CREATE TABLE DEPT_TCL 
AS SELECT * FROM DEPT D;
SELECT * FROM DEPT_TCL;

INSERT INTO DEPT_TCL VALUES(50, 'DATABASE','BUSAN');
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;
DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

-- 트랜잭션이 실행중일 때는 LOCK이 걸린다.
ROLLBACK;			-- 트랜잭션 취소
COMMIT; 			-- 트랜잭션 반영
DROP TABLE DEPT_TCL;

-- VIEW
CREATE VIEW VM_EMP AS (SELECT EMPNO, ENAME, JOB, DEPTNO FROM EMP e WHERE DEPTNO = 20);
SELECT * FROM VM_EMP;
SELECT * FROM USER_VIEWS;
DROP VIEW VM_EMP;


-- 테이블, 데이터사전, 인덱스, 뷰, 시퀀스 동의어
SELECT * FROM DICT;				-- 사용가능한 데이터 사전
SELECT TABLE_NAME FROM USER_TABLES;
SELECT OWNER, TABLE_NAME FROM ALL_TABLES;
SELECT * FROM DBA_TABLES;

-- 시퀀스
CREATE TABLE DEPT_SEQ AS SELECT * FROM DEPT d WHERE 1 != 1;
SELECT * FROM DEPT_SEQ;
DROP TABLE DEPT_SEQ;
CREATE SEQUENCE SEQ_DEPT_SEQUENCE			-- 시퀀스 테이블 이름
INCREMENT BY 10				-- 증가하는 값
START WITH 10				-- 시작 값
MAXVALUE 90					-- 최댓 값
MINVALUE 0					-- 최솟 값
NOCYCLE						-- 최대값이면 정지, 순환금지
CACHE 2;
SELECT * FROM USER_SEQUENCES;

-- 시퀀스 이름.next
INSERT INTO DEPT_SEQ (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE','BUSAN');
SELECT * FROM DEPT_SEQ;

INSERT INTO DEPT_SEQ (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE1','SEOUL');
SELECT * FROM DEPT_SEQ;
-- [시퀀스.CURRVAL] : 가장 마지막 시퀀스
INSERT INTO DEPT_SEQ (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE2','SEOUL');
SELECT * FROM DEPT_SEQ;

SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;
-- 시퀀스 수정
ALTER SEQUENCE SEQ_DEPT_SEQUENCE INCREMENT BY 3 MAXVALUE 99 CYCLE;
SELECT * FROM USER_SEQUENCES;
-- 시퀀스 삭제
DROP SEQUENCE SEQ_DEPT_SEQUENCE;
SELECT * FROM USER_SEQUENCES;

/* DDL */
-- 테이블 생성
CREATE TABLE EMP_DDL(
	EMPNO NUMBER(4),
	ENAME VARCHAR2(10),
	JOB VARCHAR2(9),
	MGR NUMBER(4),
	HIREDATE DATE,
	SAL NUMBER(7, 2),
	COMM NUMBER(7, 2),
	DEPTNO NUMBER(2)
);

CREATE TABLE EMP_DDL1 AS SELECT * FROM EMP WHERE DEPTNO = 30;
SELECT * FROM EMP_DDL1;
CREATE TABLE EMP_DDL2 AS SELECT * FROM EMP WHERE 1 != 1;
SELECT * FROM EMP_DDL2;
-- 테이블 수정
ALTER TABLE EMP_DDL1 ADD HP VARCHAR(20);				-- 열 추가
SELECT * FROM EMP_DDL1;


