SELECT ENAME, UPPER(ENAME), LOWER(ENAME) FROM emp;
SELECT ENAME, INITCAP(ENAME) FROM emp;

SELECT EMPNO ,ENAME, SAL, DEPTNO FROM emp WHERE DEPTNO = 10
UNION			-- 집합연산자
SELECT EMPNO ,ENAME, SAL, DEPTNO FROM emp WHERE DEPTNO = 20; 

SELECT EMPNO ,ENAME, SAL, DEPTNO FROM emp WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO FROM emp WHERE DEPTNO = 20;

SELECT EMPNO ,ENAME, SAL, DEPTNO FROM emp WHERE DEPTNO = 10
UNION
SELECT SAL, JOB , DEPTNO, SAL FROM emp WHERE DEPTNO = 20;		-- 열의 갯수와 데이터유형이 같아야 한다. 첫번째 SELECT문이 기준

SELECT EMPNO, ENAME, SAL, DEPTNO FROM emp 
MINUS			-- 차집합
SELECT EMPNO, ENAME, SAL, DEPTNO FROM emp WHERE DEPTNO = 10;

SELECT EMPNO, ENAME, SAL, DEPTNO FROM emp
INTERSECT		-- 교집합
SELECT EMPNO, ENAME, SAL, DEPTNO FROM emp WHERE DEPTNO = 10;

